# Generated by Django 2.2.7 on 2019-11-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20, unique=True)),
                ('u_password', models.CharField(max_length=50, unique=True)),
                ('u_tel', models.IntegerField()),
                ('u_image', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
