# Generated by Django 2.0.1 on 2019-11-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20, null=True)),
                ('u_password', models.CharField(max_length=50)),
                ('u_tel', models.IntegerField(unique=True)),
                ('u_image', models.CharField(default=None, max_length=256)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
