# Generated by Django 2.0.1 on 2019-11-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myhealth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='u_image',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='users',
            name='u_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='u_password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='u_tel',
            field=models.IntegerField(unique=True),
        ),
    ]
